name: Deploy to GitHub pages

on:
  push:
    branches:
    - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    -
      name: Install
      run: npm install
    -
       name: Test
       run: npm run test
    -
      name: Generate
      if: success()
      run: npm run build
    -
      name: Check GitHub Pages status
      if: success()
      uses: crazy-max/ghaction-github-status@v1
      with:
        pages_threshold: major_outage
    -
      name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: dist
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
